version: 2.1
jobs:
  job_1:
    docker:
      - image: circleci/php:7.3.12
    steps:
      - checkout
      - run:
          name: Generate Some File
          command: |
            mkdir folder
            echo "echo 'Hello World!! from a bash script'" > folder/a_file.sh
            chmod +x folder/a_file.sh
      - persist_to_workspace:
          root: .
          paths:
            - folder
workflows:
  version: 2
  document:
    jobs:
      - job_1
