version: 2.1
jobs:
  job_1:
    docker:
      - image: circleci/php:7.3.12
    steps:
      - checkout
      - run:
          name: Generate Some File
          command: |
            echo "Hello World!"
workflows:
  version: 2
  document:
    jobs:
      - job_1
